#Custom Archetype
!setname 0x900 SZS (Senki Zessho Symphogear)
!setname 0x901 NSO (Needy Streamer Overload)
!setname 0x902 YuYuYu (Yuki Yuna Is A Hero)
#Custom Counter
!counter 0x900a I LOVE YOU Counter
